### ISSUE TITLE
Shared environments fails on this?

### ISSUE THREAD

**Issue by jayzalowitz** [martinlindenberg/serverless-plugin-sns#11]
https://github.com/martinlindenberg/serverless-plugin-sns/blob/master/index.js#L239

Requires keys but within shared serverless environments it borks it, any wisdom as to why?

/usr/local/Cellar/nvm/0.29.0/versions/node/v5.3.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

ReferenceError: credentials is not defined
    at ServerlessPluginSNS._initAws (/Users/WWQ/workspace/tlscm/tlscm/node_modules/serverless-plugin-sns/index.js:239:29)
    at ServerlessPluginSNS._manageSNS (/Users/WWQ/workspace/tlscm/tlscm/node_modules/serverless-plugin-sns/index.js:63:19)
    at /Users/WWQ/workspace/tlscm/tlscm/node_modules/serverless-plugin-sns/index.js:44:27
    at ServerlessPluginSNS._addSNSAfterDeploy (/Users/WWQ/workspace/tlscm/tlscm/node_modules/serverless-plugin-sns/index.js:42:20)
    at next (/usr/local/Cellar/nvm/0.29.0/versions/node/v5.3.0/lib/node_modules/serverless/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete](/usr/local/Cellar/nvm/0.29.0/versions/node/v5.3.0/lib/node_modules/serverless/node_modules/rimraf/rimraf.js:110:9)

**Comment by martinlindenberg** [comment]
are you sure, that your serverless installation is working properly?

i am using a function of the serverless awsprovider to fetch the credentials. If they are not able to create the credentials object out of your data then it might be an error on your side or a bug in the serverless project. they are using this method internally as well.

```
credentials = S.getProvider('aws').getCredentials(_this.stage, region);
```
