### ISSUE TITLE
Bug: On deploy (with multiple endpoints) a new policy statement id is added each time

### ISSUE THREAD

**Issue by jayzalowitz** [martinlindenberg/serverless-plugin-sns#16]
https://github.com/martinlindenberg/serverless-plugin-sns/blob/master/index.js#L114
seems to be triggering a new statment each time i deploy.

This means that eventually if you are deploying quite a bit, you will overwhelm your policy length leading to something akin to (and im leaving this in here for reasons of google) 
`Unhandled rejection PolicyLengthExceededException: The final policy size (20761) is bigger than the limit (20480).
    at Object.extractError (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.extractError (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
    at Request.callListeners (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/your-working-directory/service-catalog-interface/node_modules/aws-sdk/lib/event_listeners.js:209:11)
    at emitNone (events.js:85:20)`

**Comment by martinlindenberg** [comment]
idea to solve this:
- use the functionname as statement id
- remove old permissions by firstly calling removePermission
- call addPermission afterwards as before

Problems:
- i did not find a way to list all available function permissions, to delete them
- old permissions will stay alive

**Comment by atzbert** [comment]
Is there any chance  this will be resolved?

**Comment by martinlindenberg** [comment]
@atzbert: Yes

i've created a new release that is now available via npm.
- it prevents the user from this problem in future
- it uses a static statementid and removes the old permission before creating a new permission. 
- BUT: didn't find a way to remove the currently existing permissions, that have been created with ealier versions that have almost unique random statement ids

**Comment by atzbert** [comment]
@martinlindenberg 
Amazingly fast! Thanks a lot. If I understand correctly the only remaining issue is that there will be lots of unused permissions which need to be removed at some point but don't do any harm either....which would be fine with me.

**Comment by martinlindenberg** [comment]
if your currently used policy length is nearly at the limit, the next deployment will add one permission to that policy which could throw that error again. 

in all other cases this issue should be solved.

if i find a way to list the policies with random statementids, i'll write a short description how to remove these permissions.

**Comment by atzbert** [comment]
works like a charm, thanks again!

**Comment by antonydenyer** [comment]
@martinlindenberg we're seeing an intermittent ResourceConflictException with this fix.

```
ResourceConflictException: The statement id (site_dev-ingestion-api-pharma-site) provided already exists. Please provide a new statement id, or remove the existing statement.
at Object.extractError (C:\BuildAgent\work\9e76427f3a53783c\node_modules\aws-sdk\lib\protocol\json.js:43:27)
  at Request.extractError (C:\BuildAgent\work\9e76427f3a53783c\node_modules\aws-sdk\lib\protocol\rest_json.js:37:8)
  at Request.callListeners (C:\BuildAgent\work\9e76427f3a53783c\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
From previous event:
  at C:\BuildAgent\work\9e76427f3a53783c\node_modules\serverless-plugin-sns\index.js:114:32
From previous event:
  at ServerlessPluginSNS._bindFunctions (C:\BuildAgent\work\9e76427f3a53783c\node_modules\serverless-plugin-sns\index.js:110:22)
  at ServerlessPluginSNS.<anonymous> (C:\BuildAgent\work\9e76427f3a53783c\node_modules\serverless-plugin-sns\index.js:79:23)
  at Request.<anonymous> (C:\BuildAgent\work\9e76427f3a53783c\node_modules\aws-sdk\lib\request.js:355:18)

```

Not sure what's going, I'm guessing the Remove hasn't finished yet.

**Comment by martinlindenberg** [comment]
Well - i think i might have found a reason. As i cannot reproduce your error i can only guess, ...

In line 113 there is a call to removePermission, where the callback function has two parameters: err and data. Currently these Parameters were ignored, and the addPermission function is called. https://github.com/martinlindenberg/serverless-plugin-sns/blob/0.5.9/index.js#L113
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#removePermission-property

If your call returns an error in removePermission, the addPermission call will fail, as the statementId already exists.

Possible reason in your setup:
`You need permission for the lambda:RemovePermission action.`
